apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::521836622611:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-107KA6LWM10K0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
   	  - system:masters
   	  rolearn: arn:aws:iam::521836622611:role/UdacityFlaskDeployCBKubectlRole
   	  username: build 
 
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-07T13:33:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1777"
  uid: aaa89ae4-9682-46a0-820f-9ef80a1da509
